GET http://localhost:8080/api/post/XD/1

###
GET http://localhost:8080/token

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "usera",
  "password": "1234"
}

###
POST http://localhost:8080/login/refresh_token


###

###
POST http://localhost:8080/logout

###
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "username": "usera",
  "password": "1234"
}

###
DELETE http://localhost:8080/api/user/11

###
PATCH http://localhost:8080/api/user?newUsername=newUsername

###
PATCH http://localhost:8080/api/user/4?username=newUsername

###
POST http://localhost:8080/api/post
Content-Type: application/json
X-Csrf-Token: ChVrEuSXzgHF02lCJmweFdPFIWiwaJgfG6nrp5_kt53zUHEsbC1Sd4Hx

{
  "text": "Example comment"
}

###
PATCH http://localhost:8080/api/post
Content-Type: application/json

{
  "postId": 1,
  "editedPostText": "Example comment"
}

###
DELETE http://localhost:8080/api/post?id=1

###
GET http://localhost:8080/api/profile/byUsername/usera

###
GET http://localhost:8080/api/profile/byId/1

###
GET http://localhost:8080/api/post?id=1

###
DELETE http://localhost:8080/api/post?id=4

###
GET http://localhost:8080/api/post/like?id=1

###
GET http://localhost:8080/api/post/unlike?id=1

###
GET http://localhost:8080/api/post/comments/1/?offset=0

###
GET http://localhost:8080/api/post/likes/1/?offset=0

###
PATCH http://localhost:8080/api/user/password
Content-Type: application/json

{
  "userId": 1,
  "previousPassword": "1234",
  "newPassword": "4321"
}
###
POST http://localhost:8080/api/post/like?id=1
###
POST http://localhost:8080/api/post
Content-Type: application/json
X-Csrf-Token: ChVrEuSXzgHF02lCJmweFdPFIWiwaJgfG6nrp5_kt53zUHEsbC1Sd4Hx

{
  "text": "Example comment to other comment",
  "referencedPostId": 1
}




